channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - fire=0.7.0
  - ld_impl_linux-64=2.43
  - libexpat=2.6.4
  - libffi=3.4.2
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgomp=14.2.0
  - liblzma=5.6.4
  - libmpdec=4.0.0
  - libsqlite=3.48.0
  - libuuid=2.38.1
  - libzlib=1.3.1
  - ncurses=6.5
  - openssl=3.4.1
  - pip=25.0
  - python=3.13.1
  - python_abi=3.13
  - readline=8.2
  - six=1.17.0
  - termcolor=2.5.0
  - tk=8.6.13
  - tzdata=2025a
  - pip:
      - agent==0.0.1
      - aiohappyeyeballs==2.4.6
      - aiohttp==3.11.12
      - aiosignal==1.3.2
      - aiosqlite==0.20.0
      - annotated-types==0.7.0
      - anyio==4.8.0
      - argon2-cffi==23.1.0
      - argon2-cffi-bindings==21.2.0
      - arrow==1.3.0
      - asttokens==3.0.0
      - async-lru==2.0.4
      - attrs==25.1.0
      - babel==2.17.0
      - beautifulsoup4==4.13.3
      - bleach==6.2.0
      - certifi==2025.1.31
      - cffi==1.17.1
      - charset-normalizer==3.4.1
      - click==8.1.8
      - comm==0.2.2
      - cryptography==43.0.3
      - dataclasses-json==0.6.7
      - debugpy==1.8.12
      - decorator==5.1.1
      - defusedxml==0.7.1
      - distro==1.9.0
      - dydantic==0.0.8
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - fqdn==1.5.1
      - frozenlist==1.5.0
      - greenlet==3.1.1
      - h11==0.14.0
      - httpcore==1.0.7
      - httpx==0.28.1
      - httpx-sse==0.4.0
      - idna==3.10
      - ipykernel==6.29.5
      - ipython==8.32.0
      - isoduration==20.11.0
      - jedi==0.19.2
      - jinja2==3.1.5
      - jiter==0.8.2
      - json5==0.10.0
      - jsonpatch==1.33
      - jsonpointer==3.0.0
      - jsonschema==4.23.0
      - jsonschema-rs==0.25.1
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyter-events==0.12.0
      - jupyter-lsp==2.2.5
      - jupyter-server==2.15.0
      - jupyter-server-terminals==0.5.3
      - jupyterlab==4.3.5
      - jupyterlab-pygments==0.3.0
      - jupyterlab-server==2.27.3
      - langchain==0.3.18
      - langchain-community==0.3.17
      - langchain-core==0.3.34
      - langchain-openai==0.3.4
      - langchain-text-splitters==0.3.6
      - langgraph==0.2.70
      - langgraph-api==0.0.22
      - langgraph-checkpoint==2.0.10
      - langgraph-checkpoint-sqlite==2.0.3
      - langgraph-cli==0.1.71
      - langgraph-sdk==0.1.51
      - langsmith==0.3.7
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - marshmallow==3.26.1
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.1
      - msgpack==1.1.0
      - multidict==6.1.0
      - mypy-extensions==1.0.0
      - nbclient==0.10.2
      - nbconvert==7.16.6
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - notebook==7.3.2
      - notebook-shim==0.2.4
      - numpy==2.2.2
      - openai==1.61.1
      - orjson==3.10.15
      - overrides==7.7.0
      - packaging==24.2
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - platformdirs==4.3.6
      - prometheus-client==0.21.1
      - prompt-toolkit==3.0.50
      - propcache==0.2.1
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydantic-settings==2.7.1
      - pygments==2.19.1
      - pyjwt==2.10.1
      - pypdf2==3.0.1
      - python-dateutil==2.9.0.post0
      - python-dotenv==1.0.1
      - python-json-logger==3.2.1
      - pyyaml==6.0.2
      - pyzmq==26.2.1
      - referencing==0.36.2
      - regex==2024.11.6
      - requests==2.32.3
      - requests-toolbelt==1.0.0
      - rfc3339-validator==0.1.4
      - rfc3986-validator==0.1.1
      - rich==13.9.4
      - rpds-py==0.22.3
      - send2trash==1.8.3
      - setuptools==75.8.0
      - sniffio==1.3.1
      - soupsieve==2.6
      - sqlalchemy==2.0.38
      - sse-starlette==2.1.3
      - stack-data==0.6.3
      - starlette==0.45.3
      - structlog==24.4.0
      - tavily-python==0.5.1
      - tenacity==9.0.0
      - terminado==0.18.1
      - tiktoken==0.8.0
      - tinycss2==1.4.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - trustcall==0.0.35
      - types-python-dateutil==2.9.0.20241206
      - typing-extensions==4.12.2
      - typing-inspect==0.9.0
      - uri-template==1.3.0
      - urllib3==2.3.0
      - uv==0.5.29
      - uvicorn==0.34.0
      - watchfiles==1.0.4
      - wcwidth==0.2.13
      - webcolors==24.11.1
      - webencodings==0.5.1
      - websocket-client==1.8.0
      - wikipedia==1.4.0
      - yarl==1.18.3
      - zstandard==0.23.0
