project:
  type: website
  output-dir: build
  render:
    - index.qmd
    - extend_doc.qmd
    - agent.qmd
    - local_dev.qmd
    - deployment.qmd

website: 
  title: "StopCyberviolence"
  sidebar:
    logo: "./img/logo_light.png"
    title: StopCyberviolence
    contents:
      - text: Project & Team
        href: index.qmd
        icon: circle-filled
      - text: Documentation
        icon: circle
        contents: 
          - text: "Extending the documentation"
            href: extend_doc.qmd
          - text: "Agentic framework and structure"
            href: agent.qmd
          - text: "Local development"
            href: local_dev.qmd
          - text: Deployment
            href: deployment.qmd

  site-url: "https://dataforgoodfr.github.io/13_stop_cyberviolence/"
