project:
  type: website
  output-dir: build
  render:
    - src/doc.qmd

website: 
  title: "StopCyberviolence"
  sidebar:
    title: StopCyberviolence
    contents:
      - href: src/doc.qmd
        text: Documentation
        icon: circle 