project:
  type: website
  output-dir: build
  render:
    - src/doc.qmd

website: 
  title: "StopCyberviolence"
  sidebar:
    title: StopCyberviolence
    contents:
      - href: src/doc.qmd
        text: Documentation
        icon: circle 

website:
  site-url: "https://dataforgoodfr.github.io/13_stop_cyberviolence/"