project:
  type: website
  output-dir: docs

website: 
  title: "StopCyberviolence"
  sidebar:
    title: StopCyberviolence
    contents:
      - href: src/doc.qmd
        text: Documentation
        icon: circle