[project]
name = "stop-cyberviolences"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mistralai>=1.5.0",
    "streamlit>=1.42.0",
]
