name: Render and Publish

on:
  push:
    branches:
      - bot_quarto_docs
  pull_request:
    branches:
      - bot_quarto_docs

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: chatbot/doc/
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_QUARTO_DOC_TOKEN }}