name: Render and Publish

on:
  push:
    branches:
      - bot_quarto_docs
  pull_request:
    branches:
      - bot_quarto_docs

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install pyyaml
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml

      - name: Update last modified date using .py script
        working-directory: chatbot/doc/
        run: |
          for file in $(find . -name "*.qmd")
          do
          lastmod=$(git log -1 --format="%cd" --date=iso -- "$file")
          python update_last_modified.py $file "$lastmod"
          done

      - name: Commit and push changes
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add -A
          git commit -m "Update last modified" || echo "No changes to commit"
          git push bot_quarto_docs

      - name: Set up Quarto
        uses: quarto-dev/quarto-actions/setup@v2

      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
          path: chatbot/doc/
        env:
          GITHUB_TOKEN: ${{ secrets.BUILD_QUARTO_DOC_TOKEN }}