name: Build Chainlit environment container on dispatch

on:
  workflow_dispatch:
  repository_dispatch:
    types: [chainlit_updated]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Container Registry
        uses: docker/login-action@v3
        with:
          registry: docker.io # or your registry (e.g., gcr.io, ecr.amazonaws.com)
          username: ${{ secrects.DOCKER_USERNAME }} # or your Docker Hub username
          password: ${{ secrets.DOCKERHUB_TOKEN }} # Store this in GitHub secrets

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: ./chatbot/deployment
          file: ./chatbot/deployment/chainlit_dev.Dockerfile
          push: true
          tags: |
            docker.io/${{ secrets.DOCKER_USERNAME }}/chainlit_uv:latest
          build-args: |
            BUILD_DATE=${{ github.event.repository.updated_at }}
            VERSION=${{ github.sha }}